export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED'
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'

export const FETCH_USER_REQUESTED = 'FETCH_USER_REQUESTED'
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'

export const POST_USERS_REQUESTED = 'POST_USERS_REQUESTED'
export const POST_USERS_SUCCEEDED = 'POST_USERS_SUCCEEDED'
export const POST_USERS_FAILED = 'POST_USERS_FAILED'

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED'
export const UPDATE_USER_SUCCEEDED = 'UPDATE_USER_SUCCEEDED'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED'
export const DELETE_USER_SUCCEEDED = 'DELETE_USER_SUCCEEDED'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'